---
name: Build Associations Overviews
permissions: read-all
on:
  workflow_dispatch:
  #push:
  schedule:
    - cron: "23 01 * * *"
jobs:
  my_job:
    name: Run dtvprocessing.py
    # inspired by <https://archive.ph/8Qidh>
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Install python 3.13 - preparing
        run: |
          sudo apt install software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa
      - name: Install python 3.13 - installing
        run: |
          sudo apt update
          sudo apt install python3.13
      - name: Install python 3.13 - setting alternatives
        run: |
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.13 99
          sudo update-alternatives --display python3
      # from <https://ubuntuhandbook.org/index.php/2022/10/python-3-11-released-how-install-ubuntu/>
      - name: checkout
        uses: actions/checkout@v4
      - name: Show python3 version
        run: python3 --version
      - name: Prepare poetry (and more) in Python
        run: |
          python3 -m pip install poetry cffi
          poetry self update
          poetry self lock
        # poetry-plugin-export
        # poetry self add poetry-plugin-export
      - name: Get dependencies from poetry
        run: |
          poetry config installer.only-binary typing
          poetry config installer.re-resolve true
          poetry config --list
          poetry self update
          poetry self lock
        #  poetry export --without-hashes --output=requirements.txt
      #- name: Print dependencies
      #  run: cat requirements.txt
      #- name: Install dependencies from poetry
      #  run: python3 -m pip install --only-binary typing -r requirements.txt
      - name: Run the Python Module
        run: |
          poetry config --list
          PIP_ONLY_BINARY=typing poetry install --no-root
          poetry run python3 -OO dtvprocessing.py
      # - name: Show the files
      #   run: ls -lah associations
      - name: Push to orphan branch associations
        run: |
          git checkout --orphan associations
          git config --global user.name "Dr. Bastian Ebeling"
          git config --global user.email 230051+Barry1@users.noreply.github.com
          git add -f associations/*.txt
          THEDATE=$(date)
          git commit -m "$THEDATE association files updated" associations/*.txt
          git push --force --set-upstream origin associations
      #    git checkout main
      #    git branch -D exampleoutput
