---
name: Pytest
on:
  workflow_dispatch:
#  push:
#    branches: ["main", "master"]
#  pull_request:
#    branches: ["main", "master"]
jobs:
  build:
    strategy:
      fail-fast: false # if true=default meaning break all on first failure
      matrix:
        #        python-version: ["3.10", "3.11.0-rc.1"]
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Install further (poetry) dependencies
        run: |
          python -m pip install poetry
          poetry export --with dev --without-hashes --output requirements.txt
          STATIC_DEPS=true
          STATICBUILD=true
          pip install --upgrade --requirement requirements.txt
      - name: Analysing the code with pytest
        run: pytest # -p no:pylama
