---
name: Build some results
permissions: read-all
on:
  schedule:
    - cron: "45 23 * * *"
  workflow_dispatch:
jobs:
  my_job:
    name: Run dance_result_federation_parser
    # inspired by <https://archive.ph/8Qidh>
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Install python 3.13 - preparing
        run: |
          sudo apt install software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa
      - name: Install python 3.13 - installing
        run: |
          sudo apt update
          sudo apt install python3.13 build-essential python3.13-dev libpython3.13-dev
      - name: Install python 3.13 - setting alternatives
        run: |
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.13 99
          sudo update-alternatives --display python3
      - name: checkout
        uses: actions/checkout@v4
      - name: NewPreb
        run: |
          python3 -m pip install --upgrade pip poetry cffi poetry-plugin-export ufw lxml \
            aiofiles beautifulsoup4 fastparquet joblib requests \
            git+https://github.com/Barry1/PyValueFragments.git typing-extensions
      #          poetry install --no-root
      #      - name: Prepare python environment
      #        run: |
      #          python3 -m pip install aiofiles bs4 fastparquet lxml \
      #            html5lib git+https://github.com/Barry1/PyValueFragments.git pyannotate
      - name: create results folder
        run: mkdir results
      - name: remove config
        run: rm config.toml
      - name: list files
        run: ls -lah
      - name: make the results
        run: ./makeallresults.sh
      #      - name: Results creation by Makefile - first run only for one URL
      #        run: |
      #          python -OO ./dance_result_federation_parser.py https\://www.tanzsport-biedermann.de/results/pfingsten22/index.html > BadBevensen_2022.txt
      #          make --jobs=1 --file=Makefile.githubworkflow FIRST
      #      - name: Results creation by Makefile - all others parallel
      #        run: make --keep-going --file=Makefile.githubworkflow OTHERS || true
      - name: Push to orphan branch results
        run: |
          git checkout --orphan results
          git config --global user.name "Dr. Bastian Ebeling"
          git config --global user.email 230051+Barry1@users.noreply.github.com
          git add ./*.md
          git rm --force README.md SECURITY.md
          THEDATE=$(date)
          git commit -m "$THEDATE results updated" ./*.md
          git push --force --set-upstream origin results
