---
name: Build some results
permissions: read-all
on:
  - workflow_dispatch
  - push
  #schedule:
  #  - cron: "23 01 * * *"
jobs:
  my_job:
    name: Run dtvprocessing.py
    # inspired by <https://archive.ph/8Qidh>
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Install python 3.11
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install python3.11
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 99
          sudo update-alternatives --display python3
      - name: checkout
        uses: actions/checkout@v4
      - name: Prepare python environment
        run: python3 -m pip install aiofiles bs4 fastparquet lxml joblib git+https://github.com/Barry1/PyValueFragments.git
      - name: danceComp2024
        run: python -OO ./dance_result_federation_parser.py https://ergebnisse.dancecomp.de/2024/index.htm
        # https://ergebnisse.dancecomp.de/2024/index.htm > results/danceComp_2024.md 2> danceComp_2024.err
      - name: Push to orphan branch results
        run: |
          git checkout --orphan results
          git config --global user.name "Dr. Bastian Ebeling"
          git config --global user.email 230051+Barry1@users.noreply.github.com
          git add -f results/*.md
          THEDATE=`date`
          git commit -m "$THEDATE results updated" results/*.md
          git push --force --set-upstream origin results
