---
name: Build some results
permissions: read-all
on:
  - workflow_dispatch
#  - push
#schedule:
#  - cron: "23 01 * * *"
jobs:
  my_job:
    name: Run dance_result_federation_parser
    # inspired by <https://archive.ph/8Qidh>
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Install python 3.11
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install python3.11
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 99
          sudo update-alternatives --display python3
      - name: checkout
        uses: actions/checkout@v4
      - name: Prepare python environment
        run: python3 -m pip install aiofiles bs4 fastparquet lxml html5lib git+https://github.com/Barry1/PyValueFragments.git pyannotate
      - name: create results folder
        run: mkdir results
      - name: remove config
        run: rm config.toml
      - name: BlauesBand 2023
        run: python -OO ./dance_result_federation_parser.py https://turniere.btc-gruen-gold.de/bb2023/index.htm > BlauesBand_2023.md 2> BlauesBand_2023.err
      - name: BlauesBand 2024
        run: python -OO ./dance_result_federation_parser.py https://turniere.btc-gruen-gold.de/bb2024/index.htm > BlauesBand_2024.md 2> BlauesBand_2024.err
      - name: BerlinDanceFestival 2023
        run: python -OO ./dance_result_federation_parser.py https://berlin-dance-festival.de/files/bdf/results/2023/index.htm > BDF_2023.md 2> BDR_2023.err
      - name: BerlinDanceFestival 2024
        run: python -OO ./dance_result_federation_parser.py https://berlin-dance-festival.de/files/bdf/results/2024/index.htm > BDF_2024.md 2> BDR_2024.err
      - name: danceComp 2014
        run: python -OO ./dance_result_federation_parser.py https://ergebnisse.dancecomp.de/2014/index.htm > danceComp_2014.md 2> danceComp_2014.err
      - name: danceComp 2015
        run: python -OO ./dance_result_federation_parser.py https://ergebnisse.dancecomp.de/2015/index.htm > danceComp_2015.md 2> danceComp_2015.err
      - name: danceComp 2016
        run: python -OO ./dance_result_federation_parser.py https://ergebnisse.dancecomp.de/2016/index.htm > danceComp_2016.md 2> danceComp_2016.err
      - name: danceComp 2017
        run: python -OO ./dance_result_federation_parser.py https://ergebnisse.dancecomp.de/2017/index.htm > danceComp_2017.md 2> danceComp_2017.err
      - name: danceComp 2018
        run: python -OO ./dance_result_federation_parser.py https://ergebnisse.dancecomp.de/2018/index.htm > danceComp_2018.md 2> danceComp_2018.err
      - name: danceComp 2019
        run: python -OO ./dance_result_federation_parser.py https://ergebnisse.dancecomp.de/2019/index.htm > danceComp_2019.md 2> danceComp_2019.err
      - name: danceComp 2020
        run: python -OO ./dance_result_federation_parser.py https://ergebnisse.dancecomp.de/2020/index.htm > danceComp_2020.md 2> danceComp_2020.err
      - name: danceComp 2022
        run: python -OO ./dance_result_federation_parser.py https://ergebnisse.dancecomp.de/2022/index.htm > danceComp_2022.md 2> danceComp_2022.err
      - name: danceComp 2023
        run: python -OO ./dance_result_federation_parser.py https://ergebnisse.dancecomp.de/2023/index.htm > danceComp_2023.md 2> danceComp_2023.err
      - name: danceComp 2024
        run: python -OO ./dance_result_federation_parser.py https://ergebnisse.dancecomp.de/2024/index.htm > danceComp_2024.md 2> danceComp_2024.err
      - name: Push to orphan branch results
        run: |
          git checkout --orphan results
          git config --global user.name "Dr. Bastian Ebeling"
          git config --global user.email 230051+Barry1@users.noreply.github.com
          git add *.md
          git rm --force README.md SECURITY.md
          THEDATE=`date`
          git commit -m "$THEDATE results updated" *.md
          git push --force --set-upstream origin results
